# Generated by Django 4.2.7 on 2024-01-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_rename_projectuploads_projectupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.projectupload'),
        ),
    ]
