# Generated by Django 4.2.7 on 2024-01-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_comment_project_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupload',
            name='Employee',
        ),
    ]
