# Generated by Django 4.2.7 on 2024-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_remove_projectupload_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupload',
            name='Institute',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
